const {ActionRowBuilder,ButtonBuilder,ButtonStyle,EmbedBuilder,ModalBuilder,TextInputBuilder,TextInputStyle}=require('discord.js');
const config=require('./config'); const db=require('./db'); const {createTicketChannel}=require('./ticketUtils');
const typeLabel={support:'🆘 Support Ticket',report:'⚠️ User Report',staff_application:'🛡️ Staff Application'};
function panel(){return new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId('ticket:staff_application').setLabel('Apply For Staff').setEmoji('🛡️').setStyle(ButtonStyle.Primary),new ButtonBuilder().setCustomId('ticket:support').setLabel('Support Ticket').setEmoji('🆘').setStyle(ButtonStyle.Success),new ButtonBuilder().setCustomId('ticket:report').setLabel('Report User').setEmoji('⚠️').setStyle(ButtonStyle.Danger));}
function appModal(){return new ModalBuilder().setCustomId('application_modal').setTitle('Staff Application').addComponents(...[['age','Age'],['country','Country'],['experience','Previous Staff Experience'],['reason','Why do you want staff?'],['choose_you','Why should we choose you?']].map(([id,label])=>new ActionRowBuilder().addComponents(new TextInputBuilder().setCustomId(id).setLabel(label).setStyle(TextInputStyle.Paragraph).setRequired(true).setMaxLength(1000))));}
async function button(interaction){const [,type]=interaction.customId.split(':'); if(!['support','report','staff_application'].includes(type))return;
 if(type==='staff_application') return interaction.showModal(appModal());
 const existing=await db.getOpenTicket(interaction.guild.id,interaction.user.id,type); if(existing){return interaction.reply({content:`You already have an open ${typeLabel[type]}: <#${existing.ticket_id}>`,ephemeral:true});}
 const ch=await createTicketChannel(interaction.guild,interaction.user,type); await db.createTicket({ticket_id:ch.id,guild_id:interaction.guild.id,user_id:interaction.user.id,type,status:'pending',claimed_by:null});
 const embed=new EmbedBuilder().setTitle(typeLabel[type]).setDescription(type==='report'?'Please explain the issue and provide the relevant user/message details.':'Please describe your issue. A staff member will assist you shortly.').setColor(config.colors[type==='report'?'report':'support']);
 await ch.send({content:`<@${interaction.user.id}>`,embeds:[embed],components:[new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId(`ticket:close:${ch.id}`).setLabel('Close Ticket').setEmoji('🔒').setStyle(ButtonStyle.Secondary))]}); await interaction.reply({content:`Your ticket has been created: <#${ch.id}>`,ephemeral:true});}
async function application(interaction){const vals=Object.fromEntries(['age','country','experience','reason','choose_you'].map(k=>[k,interaction.fields.getTextInputValue(k)]));const existing=await db.getOpenTicket(interaction.guild.id,interaction.user.id,'staff_application');if(existing)return interaction.reply({content:`You already have an open application: <#${existing.ticket_id}>`,ephemeral:true});const ch=await createTicketChannel(interaction.guild,interaction.user,'staff_application');await db.createTicket({ticket_id:ch.id,guild_id:interaction.guild.id,user_id:interaction.user.id,type:'staff_application',status:'pending',claimed_by:null});await db.createApplication({user_id:interaction.user.id,age:vals.age,country:vals.country,experience:vals.experience,reason:vals.reason,choose_you:vals.choose_you,status:'Pending',interviewer_id:null,interview_vc:null});const embed=new EmbedBuilder().setTitle('🛡️ Staff Application').setDescription(Object.entries(vals).map(([k,v])=>`**${k.replace('_',' ')}**\n${v}`).join('\n\n')).setColor(config.colors.staff);const queue=await interaction.guild.channels.fetch(config.channels.applicationQueue);await queue.send({content:`<@&${config.roles.interviewer}>`,embeds:[embed],components:[new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId(`application:accept:${interaction.user.id}:${ch.id}`).setLabel('Accept Interview').setStyle(ButtonStyle.Success),new ButtonBuilder().setCustomId(`application:reject:${interaction.user.id}:${ch.id}`).setLabel('Reject').setStyle(ButtonStyle.Danger))]});await ch.send({content:`<@${interaction.user.id}> Your application has been submitted. Please wait for an interviewer.`});await interaction.reply({content:`Application submitted: <#${ch.id}>`,ephemeral:true});}
async function close(interaction){const parts=interaction.customId.split(':');const ch=interaction.channel;await db.updateTicket(ch.id,{status:'closed'}).catch(()=>{});await interaction.reply({content:'Ticket is being closed...',ephemeral:true});setTimeout(()=>ch.delete().catch(()=>{}),1500);}
async function applicationAction(interaction){const [,action,userId,ticketId]=interaction.customId.split(':');if(!interaction.member.roles.cache.has(config.roles.interviewer)&&!interaction.member.roles.cache.has(config.roles.admin))return interaction.reply({content:'You do not have permission to manage applications.',ephemeral:true});if(action==='reject'){await db.updateApplication(userId,{status:'Rejected',interviewer_id:interaction.user.id});await db.updateTicket(ticketId,{status:'rejected',claimed_by:interaction.user.id});return interaction.reply({content:'Application rejected.',ephemeral:true});}const guild=interaction.guild;const applicant=await guild.members.fetch(userId);const vc=await guild.channels.create({name:`Interview - ${applicant.user.username}`,type:2,parent:config.categories.tickets,permissionOverwrites:[{id:guild.roles.everyone.id,deny:['ViewChannel']},{id:userId,allow:['ViewChannel','Connect','Speak']},{id:interaction.user.id,allow:['ViewChannel','Connect','Speak']},{id:config.roles.admin,allow:['ViewChannel','Connect','Speak']}]});await db.updateApplication(userId,{status:'Interview Scheduled',interviewer_id:interaction.user.id,interview_vc:vc.id});await db.updateTicket(ticketId,{status:'interview_scheduled',claimed_by:interaction.user.id});await vc.send(`Interview scheduled. Applicant: <@${userId}> | Interviewer: <@${interaction.user.id}>`);await interaction.reply({content:`Interview VC created: <#${vc.id}>`,ephemeral:true});}
module.exports={panel,button,application,close,applicationAction};
